name: "Execute CI/CD Scan"
on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20"

      - name: Run GitHub Action
        id: scan
        uses: DSDO01/ci-cd-playground/actions/github@main
        with:
          API_TOKEN: dedge_pat_acNkC5G3_uB-enAbdVP_nkEjL6RmVfYCHcC8C9WXovU=
          DEDGE_HOST_URL: https://api.dedge.dedgesecurity.io
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASSET_ID: ${{ vars.ASSET_ID }} # This field is optional, if you would like to trigger a scan on a specific asset.
